<?php 
return [
    ['sector' => 'Portaria', 'localization' => 'x Andar'],
    ['sector' => 'Corregedor', 'localization' => 'x Andar'],
    ['sector' => 'Corregedor Adjunto', 'localization' => 'x Andar'],
    ['sector' => 'Coordenador SPPA/SPJM', 'localization' => 'x Andar'],
    ['sector' => 'Chefe PPAdm e PJM', 'localization' => 'x Andar'],
    ['sector' => 'Analistas', 'localization' => 'x Andar'],
    ['sector' => 'Tecnologia e TCIP', 'localization' => 'x Andar'],
    ['sector' => 'Informática', 'localization' => 'x Andar'],
    ['sector' => 'Comissão Processante Permanente', 'localization' => 'x Andar'],
    ['sector' => 'Cartório PPAdm', 'localization' => 'x Andar'],
    ['sector' => 'Cartório PJM', 'localization' => 'x Andar'],
    ['sector' => 'Inquérito Técnico', 'localization' => 'x Andar'],
    ['sector' => 'Distribuição/Arquivo', 'localization' => 'x Andar'],
    ['sector' => 'Protocolo', 'localization' => 'x Andar'],
    ['sector' => 'P/1', 'localization' => 'x Andar'],
    ['sector' => 'P/4', 'localization' => 'x Andar'],
    ['sector' => 'Chefia SAI', 'localization' => 'x Andar'],
    ['sector' => 'SAI Adm.', 'localization' => 'x Andar'],
    ['sector' => 'SAI Operações.', 'localization' => 'x Andar'],
    ['sector' => 'SUBCORREGEDORIAS', 'localization' => 'x Andar'],
    ['sector' => 'GAECOS', 'localization' => 'x Andar'],
];